default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  database: tv-today-test

production:
  <<: *default
  url: <%= Heron.TVTODAY_DATABASE_URL %>
