default: &default
  adapter: postgresql
  encoding: unicode
  username: justindoody
  password: justin33!
  database: tv-today
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  adapter: mysql2
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
