default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  database: postgres
  pool: 5
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  adapter: mysql2
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
