# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14b64ef16e12a6c237bafa5e3c581122a63802e167c91a77db97d47ba15ef6cd16747b8f27e773736ac4821a0e323884a0db18cda4ba91c4aa97e230928d937b

test:
  secret_key_base: 40c4cf8c4fe12cba508f305b57b331f6b5499b4797a38a3f5aa500eefe58d94619aada90238192b1a5584cf3ab128d12305d05cbdc95aa86cd5b0da282a34f78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
